# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9jEM1NwuMVaWdbootx7LD8nHUVvMx6i

ANN

Data Processing

Importing Libraries
"""